# Top level build commands, using https://github.com/devzendo/releaselite/
version: 1.0.1

clean: rm -rf cmake-build-release; rm -rf cmake-build-debug

prepare: mkdir -p cmake-build-release; (cd cmake-build-release && cmake -G 'Unix Makefiles' ..)
unless: -e cmake-build-release

compile: cmake --build cmake-build-release --target all

test: cd cmake-build-release; ctest --test-action Test --parallel 14 --verbose

